### ISSUE TITLE
Non richiedere commenti ulteriori se lo stato è ok

### ISSUE THREAD

**Issue by tommyblue** [MaoX17/strails#42]
Se vado a inserire un commento con valutazione "Tutto ok" non dovrebbero essere richiesti ulteriori dati per poter salvare

**Comment by MaoX17** [comment]
Riflettendo direi che potrei aggiungere un completamento automatico del commento de si sceglie "Tutto ok"
In questo modo i trail builder che vogliono segnalare il ripristino di un sentiero possono comunque aggiungere le informazioni aggiuntive che vogliono per dare maggiori dettagli
